### ISSUE TITLE
do you have this code in python?

### ISSUE THREAD

**Issue by Sandy4321** [amkatrutsa/QPFeatureSelection#1]
will it work for logistic regression?
do you have this code in python?

**Comment by amkatrutsa** [comment]
1. Logistic regression is just an approach to state a classification problem. Therefore, the proposed feature selection approach can improve the stability of the computations during SGD optimization to find the logistic regression parameter vector.
2. No, I do not have this code in Python. But you can easily re-implement it with [cvxpy](https://www.cvxpy.org/) package

**Comment by Sandy4321** [comment]
cvxpy is mistaken conceptually
see this 
https://stackoverflow.com/questions/57244206/interior-point-m-cvxpy-logistic-regression-does-not-reconstruct-regression-coeff 
and
https://github.com/cvxgrp/cvxpy/issues/775

cvxpy even does not care to test if coefficients are reconstructed

**Comment by Sandy4321** [comment]
do you code which can reconstruct coefficients for logistic regression
for example to  pass this test

**Comment by Sandy4321** [comment]
https://github.com/vene/pyowl
![image](https://user-images.githubusercontent.com/11426119/63896603-7a0bac80-c9c0-11e9-9c3e-fbe23fa71728.png)

**Comment by SteveDiamond** [comment]
@Sandy4321 I apologize for not taking your concerns seriously. I have fixed the cvxpy logistic regression example. There was a second bug in it. Let me know if you are satisfied.

**Comment by amkatrutsa** [comment]
@Sandy4321 Thank you for reporting about the bug in cvxpy examples. I hope it is fixed now.
